### ISSUE TITLE
reloadItems panel cannot be hovered or clicked

### ISSUE THREAD

**Issue by ChuHoMan** [tjx666/reload-can-solve-any-problems#2]
The "reloadItems" panel cannot be hovered or clicked. My vscode version is `1.78.0`. I remember it was still working before the last vscode update.

## context
Reload Can Solve Any Problems extensions version: 0.1.2

![1021181683773733_ pic](https://github.com/tjx666/reload-can-solve-any-problems/assets/74137084/e483e332-2c4f-4779-a7b1-d2bdd99ca304)

**Comment by puppet-666** [comment]
[vscode statusBarItem](https://github.com/microsoft/vscode/issues/181606)

**Comment by ChuHoMan** [comment]
OK, The current workaround is to hold down 'option' to "lock" it in place after waiting for the panel to call out that it doesn't hide when hovered.🙂

**Comment by tjx666** [comment]
fixed in latest vscode version
